# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [27]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [37]:
# Loan CSV file generated from WeatherPy Folder
weather_df2_to_load = "weather_df2.csv"
weather_df2 = pd.read_csv(weather_df2_to_load)
dropna_weather_df2 = weather_df2.dropna()
dropna_weather_df2.head(20)

,City_ID,City,Cloudiness,Country,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,ostrovnoy,2,RU,72,68.05,39.51,37.50,7.16
1,1,mahebourg,75,MU,74,-20.41,57.70,78.80,11.41
2,2,qaanaaq,25,GL,73,77.48,-69.36,22.20,2.37
3,3,zhuhai,0,CN,39,40.71,112.04,44.60,4.47
4,4,cape town,20,ZA,76,-33.93,18.42,55.99,8.05
5,5,atuona,78,PF,76,-9.80,-139.03,81.96,16.49
6,6,flinders,0,AU,62,-34.58,150.85,60.01,11.41
8,8,tiksi,95,RU,88,71.64,128.87,14.10,15.70
9,9,pushkinskiye gory,6,RU,70,57.02,28.91,65.04,6.93
10,10,aykhal,90,RU,48,65.95,111.51,39.20,11.18
11,11,castro,0,CL,70,-42.48,-73.76,48.20,9.17
12,12,avarua,100,CK,94,-21.21,-159.78,71.60,2.24
13,13,saskylakh,0,RU,91,71.97,114.09,4.92,2.26
14,14,constitucion,5,MX,4,23.99,-104.67,84.20,16.11
15,15,albany,40,US,45,42.65,-73.75,82.40,12.75
16,16,vilyuysk,16,RU,59,63.75,121.63,34.62,5.84
17,17,ushuaia,75,AR,75,-54.81,-68.31,44.60,36.91
18,18,bambous virieux,75,MU,74,-20.34,57.76,78.80,11.41
19,19,kodinsk,14,RU,81,58.60,99.18,48.84,4.97
20,20,teknaf,1,BD,85,20.86,92.31,84.66,8.23

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [80]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# locations
locations = dropna_weather_df2[["Lat","Lng","Humidity"]].astype(float)

In [88]:
# Plot Heatmap
fig = gmaps.figure()

# Add layer = "fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [120]:
# Filter vacation with max temp above 70 degrees F

# Filter vacation with max temp below 80 degrees F

# Filter vacation with wind speed below 10 mph

# Filter vacation with humidity below 60 %

# Set Index

In [121]:
# Plot Heatmap
vaca_fig = gmaps.figure()

# Add layer
vaca_fig.add_layer

# Display figure
vaca_fig

Figure(layout=FigureLayout(height='420px'))

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [122]:
# Hotel variable
hotels = []

# Loop through narrowed down dataframe to get nearest hotel

# Dataframe with nearest hotel

In [123]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name

In [124]:
# Add marker layer ontop of heat map

# Display Map
vaca_fig

Figure(layout=FigureLayout(height='420px'))